apiVersion: v1
kind: ConfigMap
metadata:
  name: test-topic
  labels:
    strimzi.io/kind: topic
    strimzi.io/cluster: my-cluster
data:
  name: test-topic
  partitions: "3"
  replicas: "3"
  config: |-
    {
      "retention.bytes": "1073741824",
      "retention.ms": "86400000",
      "segment.bytes": "1073741824"
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: dimitraz/go-producer:latest
        env:
          - name: SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: test-topic
          - name: TIMER
            value: "1000"
          - name: NUMBER_OF_KEYS
            value: "3"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: dimitraz/go-consumer:latest
        env:
          - name: SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: test-topic
          - name: GROUP_ID
            value: kafka-consumer